-- -- Users table seeds here (Example)
-- INSERT INTO users (name, email, password) VALUES ('Alice', "alice@yahoo.com", "password");
-- INSERT INTO users (name, email, password) VALUES ('Kira', "kslice@gmail.com", "password");
-- INSERT INTO users (name, email, password) VALUES ('Teddy', "tedsteroni@gmail.com", "password");
