INSERT INTO comments (user_id, resource_id, comment) VALUES (3, 5, 'Great video!');
INSERT INTO comments (user_id, resource_id, comment) VALUES (1, 12, 'Amazing content!');
INSERT INTO comments (user_id, resource_id, comment) VALUES (2, 1, 'Nice job!');
INSERT INTO comments (user_id, resource_id, comment) VALUES (1, 6, 'Very informative.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (3, 2, 'Loved this!');
INSERT INTO comments (user_id, resource_id, comment) VALUES (2, 9, 'Thanks for sharing.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (1, 10, 'Awesome work!');
INSERT INTO comments (user_id, resource_id, comment) VALUES (3, 7, 'This helped me a lot.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (2, 4, 'Impressive!');
INSERT INTO comments (user_id, resource_id, comment) VALUES (3, 15, 'Really enjoyed it!');
INSERT INTO comments (user_id, resource_id, comment) VALUES (2, 3, 'Well explained.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (1, 8, 'I learned something new.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (3, 11, 'Keep up the good work!');
INSERT INTO comments (user_id, resource_id, comment) VALUES (2, 24, 'This video deserves more views.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (1, 13, 'Excellent tutorial!');
INSERT INTO comments (user_id, resource_id, comment) VALUES (3, 17, 'Really helpful information.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (2, 20, 'Well done!');
INSERT INTO comments (user_id, resource_id, comment) VALUES (1, 16, 'I couldnt agree more.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (3, 14, 'Thumbs up!');
INSERT INTO comments (user_id, resource_id, comment) VALUES (2, 22, 'This video answered my questions.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (1, 18, 'Impressive explanation.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (3, 21, 'Very insightful.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (2, 19, 'Thanks for the tutorial.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (1, 23, 'This video is a game-changer.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (3, 24, 'Cant believe I have not found this earlier.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (1, 7, 'I am impressed!');
INSERT INTO comments (user_id, resource_id, comment) VALUES (3, 16, 'This is exactly what I needed.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (2, 13, 'Really well explained.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (1, 19, 'Very helpful tutorial.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (3, 3, 'Awesome video!');
INSERT INTO comments (user_id, resource_id, comment) VALUES (2, 10, 'I learned a lot from this.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (1, 5, 'This video deserves more likes!');
INSERT INTO comments (user_id, resource_id, comment) VALUES (3, 9, 'Great explanation.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (2, 11, 'This is gold!');
INSERT INTO comments (user_id, resource_id, comment) VALUES (1, 20, 'Very well presented.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (3, 8, 'Exactly what I was looking for.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (2, 15, 'Amazing video!');
INSERT INTO comments (user_id, resource_id, comment) VALUES (1, 21, 'This is so helpful.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (3, 6, 'Great job!');
INSERT INTO comments (user_id, resource_id, comment) VALUES (2, 14, 'Thanks for sharing this.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (1, 23, 'This is really valuable.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (3, 4, 'This video made my day.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (2, 18, 'I am blown away by this.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (1, 16, 'Incredible work!');
INSERT INTO comments (user_id, resource_id, comment) VALUES (3, 7, 'I wish I had found this sooner.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (2, 12, 'This is pure gold.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (1, 9, 'Thank you for this.');
INSERT INTO comments (user_id, resource_id, comment) VALUES (3, 2, 'This is amazing!');
